services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dentist-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${MSSQL_SA_PASSWORD}' -No -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 3s
      retries: 10

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Server=db,1433;Database=DentistBooking;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true;"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mssqldata:
      
    